package com.inventory.models;

/**
 * OOP: POJO (Plain Old Java Object) / Entity Class
 * This class represents a 'User' entity in the system. It follows the 
 * Data Transfer Object (DTO) pattern to move user data between the 
 * database and the web interface.
 */
public class User {

    /**
     * OOP: Encapsulation
     * By using 'private' modifiers, we hide the internal data from outside 
     * classes, ensuring that the object's state can only be changed via methods.
     */
    private int userId;           // Logic: Holds the Primary Key value from the database 'users' table.
    private String username;      // Logic: Stores the unique identifier for user login.
    private String passwordHash;  // Logic: Stores the hashed (encrypted) string, not the plain-text password.
    private String role;          // Logic: Used for Authorization (RBAC) to distinguish ADMIN from STAFF.

    /**
     * OOP: Accessor Method (Getter)
     * Logic: Provides a public way to read the private userId value.
     */
    public int getUserId() { 
        return userId; 
    }

    /**
     * OOP: Mutator Method (Setter)
     * Logic: Allows the DAO layer to inject the ID retrieved from the database into this object.
     */
    public void setUserId(int userId) { 
        this.userId = userId; // 'this' keyword resolves the conflict between parameter name and field name.
    }

    /**
     * OOP: Encapsulation - Controlled Access
     * Logic: Returns the username string for display or authentication checks.
     */
    public String getUsername() { 
        return username; 
    }

    /**
     * Logic: Updates the username property of the specific User instance.
     */
    public void setUsername(String username) { 
        this.username = username; 
    }

    /**
     * Logic: Retrieves the hashed password for comparison during the login process.
     */
    public String getPasswordHash() { 
        return passwordHash; 
    }

    /**
     * Logic: Sets the passwordHash. This value is usually generated by the PasswordUtil utility.
     */
    public void setPasswordHash(String passwordHash) { 
        this.passwordHash = passwordHash; 
    }

    /**
     * OOP: Role-Based Access Control (RBAC) Property
     * Logic: Returns the user's role string to be checked by Security Filters.
     */
    public String getRole() { 
        return role; 
    }

    /**
     * Logic: Assigns a security role to the user (e.g., assigning 'ADMIN' gives higher privileges).
     */
    public void setRole(String role) { 
        this.role = role; 
    }
}